
const actionsTypes = {
  ADD_POST: 'ADD_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  VOTE_POST: 'VOTE_POST',
  SORT_POST: 'SORT_POST',
  CATEGORY_FILTER: 'CATEGORY_FILTER',
  ADD_COMMENT: 'ADD_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  VOTE_COMMENT: 'VOTE_COMMENT',
  SORT_COMMENT: 'SORT_COMMENT',
}

export default actionsTypes
