
const actionsTypes = {
  LOAD_POSTS: 'LOAD_POSTS',
  ADD_POST: 'ADD_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST',
  VOTE_POST: 'VOTE_POST',
  VOTE_POST_DOWN: 'VOTE_POST_DOWN',
  SORT_POSTS: 'SORT_POSTS',
  CATEGORY_FILTER: 'CATEGORY_FILTER',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
  VOTE_COMMENT: 'VOTE_COMMENT',
  VOTE_COMMENT_DOWN: 'VOTE_COMMENT_DOWN',
  SORT_COMMENTS: 'SORT_COMMENTS',
  SET_USER: 'SET_USER',
  LOAD_CATEGORIES: 'LOAD_CATEGORIES',
}

export default actionsTypes
